import type { Metadata } from "next";
import "./globals.css";
import "antd/dist/reset.css";
import { ThemeProvider } from "@/theme/ThemeProvider";
import AppLayout from "@/components/layout/AppLayout";



export const metadata: Metadata = {
  title: "Makert Place",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <AppLayout>
          {children}
          </AppLayout>
        </ThemeProvider>
     </body>
    </html>
  );
}
