import { DeliveryType } from "@/types/types";

export const deliveriesData: DeliveryType[] = [
  {
    orderId: "DLV-3001",
    userId: "USR-501",
    restaurantName: "Spice Kitchen",
    status: "Delivered",
    totalAmount: 850,
    deliveryFee: 50,
    deliveryTime: 40,
    items: 4,
    deliveryAddress: "Gachibowli, Hyderabad",
    createdAt: "2025-12-11",
    updatedAt: "2025-12-11",
    attachment: {
      name: "Food Image",
      img: "https://via.placeholder.com/100",
      description: "Photo of delivered items",
    },
  },
  {
    orderId: "DLV-3002",
    userId: "USR-502",
    restaurantName: "Burger Hub",
    status: "Out for Delivery",
    totalAmount: 600,
    deliveryFee: 30,
    deliveryTime: 25,
    items: 2,
    deliveryAddress: "Koramangala, Bangalore",
    createdAt: "2025-12-12",
    updatedAt: "2025-12-12",
    attachment: {
      name: "Order Receipt",
      img: "https://via.placeholder.com/100",
      description: "Snapshot of order bill",
    },
  },
  {
    orderId: "DLV-3003",
    userId: "USR-503",
    restaurantName: "South Delights",
    status: "Preparing",
    totalAmount: 1200,
    deliveryFee: 60,
    deliveryTime: 50,
    items: 5,
    deliveryAddress: "Adyar, Chennai",
    createdAt: "2025-12-13",
    updatedAt: "2025-12-13",
    attachment: {
      name: "Menu Snapshot",
      img: "https://via.placeholder.com/100",
      description: "Image from restaurant menu",
    },
  },
  {
    orderId: "DLV-3004",
    userId: "USR-504",
    restaurantName: "Pizza Palace",
    status: "Cancelled",
    totalAmount: 400,
    deliveryFee: 20,
    deliveryTime: 30,
    items: 1,
    deliveryAddress: "Andheri, Mumbai",
    createdAt: "2025-12-10",
    updatedAt: "2025-12-10",
    attachment: {
      name: "Cancellation Note",
      img: "https://via.placeholder.com/100",
      description: "Refund details snapshot",
    },
  },
];