// utils/inventoryData.ts
import { InventoryType } from "@/types/types";

export const inventoryDefault: InventoryType[] = [
  {
    productId: "PROD-001",
    name: "Wireless Keyboard",
    description: "Slim wireless keyboard with silent keys.",
    price: 1499,
    category: "Electronics",
    stock: 120,
    createdAt: "2025-01-10",
    updatedAt: "2025-01-20",
    image: "/images/keyboard.jpg",
    productSchemaInitial: "v1",
    productSchemeCurrent: "v2",
  },
  {
    productId: "PROD-002",
    name: "Bluetooth Speaker",
    description: "Portable speaker with deep bass.",
    price: 2499,
    category: "Audio",
    stock: 45,
    createdAt: "2025-01-05",
    updatedAt: "2025-01-18",
    image: "/images/speaker.jpg",
    productSchemaInitial: "v1",
    productSchemeCurrent: "v3",
  },
  {
    productId: "PROD-003",
    name: "Smart Watch",
    description: "Waterproof smart watch with health tracking.",
    price: 4999,
    category: "Wearables",
    stock: 78,
    createdAt: "2025-01-02",
    updatedAt: "2025-01-22",
    image: "/images/smartwatch.jpg",
    productSchemaInitial: "v1",
    productSchemeCurrent: "v1.2",
  },
  {
    productId: "PROD-004",
    name: "Gaming Mouse",
    description: "RGB gaming mouse with 6 programmable buttons.",
    price: 1299,
    category: "Gaming",
    stock: 200,
    createdAt: "2025-01-08",
    updatedAt: "2025-01-25",
    image: "/images/mouse.jpg",
    productSchemaInitial: "v1",
    productSchemeCurrent: "v2",
  },
  {
    productId: "PROD-005",
    name: "Noise Cancelling Headphones",
    description: "Over-ear headphones with ANC.",
    price: 7999,
    category: "Audio",
    stock: 12,
    createdAt: "2025-01-01",
    updatedAt: "2025-01-26",
    image: "/images/headphones.jpg",
    productSchemaInitial: "v1",
    productSchemeCurrent: "v2.1",
  },
];
