import { TradeType } from "@/types/types";

export const tradesData: TradeType[] = [
  {
    tradeId: "TRD-4001",
    userId: "USR-501",
    stockSymbol: "RELIANCE",
    tradeType: "Buy",
    status: "Executed",
    totalAmount: 25000,
    quantity: 10,
    marketPrice: 2500,
    executedAt: "2025-12-13",
    updatedAt: "2025-12-13",
    attachment: {
      name: "Stock Chart",
      img: "https://via.placeholder.com/100",
      description: "Price chart at execution",
    },
  },
  {
    tradeId: "TRD-4002",
    userId: "USR-502",
    stockSymbol: "TCS",
    tradeType: "Sell",
    status: "Pending",
    totalAmount: 18000,
    quantity: 5,
    marketPrice: 3600,
    executedAt: "2025-12-12",
    updatedAt: "2025-12-12",
    attachment: {
      name: "Trade Confirmation",
      img: "https://via.placeholder.com/100",
      description: "Snapshot of trade details",
    },
  },
  {
    tradeId: "TRD-4003",
    userId: "USR-503",
    stockSymbol: "INFY",
    tradeType: "Buy",
    status: "Executed",
    totalAmount: 15000,
    quantity: 15,
    marketPrice: 1000,
    executedAt: "2025-12-11",
    updatedAt: "2025-12-11",
    attachment: {
      name: "Market News",
      img: "https://via.placeholder.com/100",
      description: "Related news snippet image",
    },
  },
  {
    tradeId: "TRD-4004",
    userId: "USR-504",
    stockSymbol: "HDFC",
    tradeType: "Sell",
    status: "Cancelled",
    totalAmount: 12000,
    quantity: 8,
    marketPrice: 1500,
    executedAt: "2025-12-10",
    updatedAt: "2025-12-10",
    attachment: {
      name: "Cancellation Slip",
      img: "https://via.placeholder.com/100",
      description: "Trade cancellation record",
    },
  },
];