import {TripType} from '@/types/types'

export const tripsData: TripType[] = [
  {
    tripId: "TRP-2001",
    userId: "USR-501",
    driverId: "DRV-101",
    status: "Completed",
    totalFare: 450,
    distance: 12.5,
    estimatedTime: 25,
    pickupLocation: "Hyderabad Airport, Telangana",
    dropoffLocation: "Hitech City, Hyderabad",
    createdAt: "2025-12-10",
    updatedAt: "2025-12-10",
    attachment: {
      name: "Route Map",
      img: "https://via.placeholder.com/100",
      description: "Snapshot of trip route",
    },
  },
  {
    tripId: "TRP-2002",
    userId: "USR-502",
    driverId: "DRV-102",
    status: "En Route",
    totalFare: 320,
    distance: 8.2,
    estimatedTime: 15,
    pickupLocation: "MG Road, Bangalore",
    dropoffLocation: "Indiranagar, Bangalore",
    createdAt: "2025-12-12",
    updatedAt: "2025-12-12",
    attachment: {
      name: "Driver Profile",
      img: "https://via.placeholder.com/100",
      description: "Image of assigned driver",
    },
  },
  {
    tripId: "TRP-2003",
    userId: "USR-503",
    driverId: "DRV-103",
    status: "Waiting",
    totalFare: 600,
    distance: 15.0,
    estimatedTime: 30,
    pickupLocation: "Marina Beach, Chennai",
    dropoffLocation: "Anna Nagar, Chennai",
    createdAt: "2025-12-13",
    updatedAt: "2025-12-13",
    attachment: {
      name: "Vehicle Photo",
      img: "https://via.placeholder.com/100",
      description: "Image of the ride vehicle",
    },
  },
  {
    tripId: "TRP-2004",
    userId: "USR-504",
    driverId: "DRV-104",
    status: "Cancelled",
    totalFare: 200,
    distance: 5.0,
    estimatedTime: 10,
    pickupLocation: "Gateway of India, Mumbai",
    dropoffLocation: "Bandra, Mumbai",
    createdAt: "2025-12-09",
    updatedAt: "2025-12-09",
    attachment: {
      name: "Cancellation Receipt",
      img: "https://via.placeholder.com/100",
      description: "Snapshot of cancellation details",
    },
  },
];